### ISSUE TITLE
Currency styling 

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/pure-site#150]
when you lay out pricing, it’s smart to place the currency symbol in a separate span and the ,– also, so they can be styled separately (e.g. currency smaller and aligned to the top, ,– smaller and aligned to the bottom).

Not sure if there is a way where you can avoid adding spans for this. Prob not.

**Comment by jamesalley** [comment]
This wheel hasn't squeaked in so long, I'm inclined to close it. If anyone reopens it, please provide more detail, such as where in the site we render currency values. I would expect an issue like this to be opened against FormatJS, not Pure! ;-)
