### ISSUE TITLE
Make layout examples public domain

### ISSUE THREAD

**Issue by ciupicri** [yahoo/pure-site#177]
The current license of the [layout examples](http://purecss.io/layouts/) is _BSD_, which makes compliance a bit harder than if they would be _public domain_.

**Comment by gyehuda** [comment]
We're licensing the layout examples under the zLib. No worries about compliance.

**Comment by redonkulus** [comment]
@ciupicri just a final follow up, https://github.com/yahoo/pure-site/commit/335b066e0de8d316391016619235849ac0ec8961 added the proper license information.
