### ISSUE TITLE
Menus breaks with iOS 7

### ISSUE THREAD

**Issue by okuryu** [yahoo/pure-site#186]
[Menus page](http://purecss.io/menus/) breaks with iOS 7.x Safari.

![img_0139](https://f.cloud.github.com/assets/34588/1973884/569508f8-8364-11e3-94b1-12dd6d2841aa.PNG)

**Comment by jamesalley** [comment]
I think this is a non-issue since the last release, when the menus page was overhauled with a new menu system.

**Comment by okuryu** [comment]
Yeah, it looks resolved this issue now. :+1:
