### ISSUE TITLE
Add #purecss IRC channel info

### ISSUE THREAD

**Issue by ericf** [yahoo/pure-site#203]
We should add the #purecss IRC Freenode channel info to the website. Not sure where though :-/

**Comment by Jzarecta** [comment]
I have visited many times but is always empty.

**Comment by jamesalley** [comment]
There is no one there. Probably when Tilo and Eric were actively developing Pure they would hang out there, but no longer. I've been relying on GitHub, Twitter, and Gitter, the latter of which offers real-time chat. I should probably add a Gitter link to the ReadMe at pure-site.
