### ISSUE TITLE
 Marketing layout header appears on two lines in Chrome.

### ISSUE THREAD

**Issue by fuzzytern** [yahoo/pure-site#246]
As described in [issue #320 in the Pure Source Repository](https://github.com/yui/pure/issues/320).

**Comment by rixlabs** [comment]
SO this issue and the #311 are closed with no solution?

**Comment by fliiiix** [comment]
Well there is a "[solution]( https://github.com/yahoo/pure/issues/320#issuecomment-52738644 )". 
And this bug is not closed only #311 and #499 are closed, because there duplicates of this issue.

**Comment by ismarS** [comment]
It would appear that this issue has been fixed sometime during the updates, or am I missing something? 

![image](https://cloud.githubusercontent.com/assets/23704250/20623762/7cfc3fac-b309-11e6-8296-36b65aa98737.png)

**Comment by rixlabs** [comment]
yep. Changed name and it's working, at least for me :)

**Comment by redonkulus** [comment]
Ok please reopen if issue occurs again.
