### ISSUE TITLE
Image gallery distorts and crops images

### ISSUE THREAD

**Issue by nathanaeljones** [yahoo/pure-site#288]
The Gallery layout is extremely broken. Scaling the browser window causes images to be distorted (aspect ratio is lost), and to be cropped at the bottom.

This poor demo reflects badly on Pure, and gives new users a hard time. 

Could this be replaced with a correct demo? If so, what would the acceptance criteria be for a pull request?

**Comment by redonkulus** [comment]
Fixed via https://github.com/yahoo/pure-site/pull/350
