### ISSUE TITLE
Pure-site's menus jumpy in IE11

### ISSUE THREAD

**Issue by jamesalley** [yahoo/pure-site#290]
As I click on the menu items, they flicker and animate, sliding in from the left. But not with every click; with some clicks this does not happen. Clearly IE is acting up, but we should investigate what is happening here. Is there some slow JS class application client-side? Is there an MS-transition there we can remove? Is IE11 slow at handling media queries and thus rendering the menu?

**Comment by gvandam** [comment]
I had the same problem with my copy of http://purecss.io/layouts/side-menu/.

As long as IE can't handle transitions correctly, I am fixing it in side-menu.css by changing

#layout,
#menu,
.menu-link {
    -webkit-transition: all 0.2s ease-out;
    -moz-transition: all 0.2s ease-out;
    -ms-transition: all 0.2s ease-out;
    -o-transition: all 0.2s ease-out;
    transition: all 0.2s ease-out;
}

into

#layout,
#menu,
.menu-link {
    -webkit-transition: all 0.2s ease-out;
    -moz-transition: all 0.2s ease-out;
    -o-transition: all 0.2s ease-out;
    transition: all 0.2s ease-out;
    -ms-transition: all 0s ease-out; /* IE */
}

It's better that way, although you'll loose the smooth transitions.

**Comment by redonkulus** [comment]
Tried this on my IE 11 VM, did not see the same issue. Please comment if the problem still exists.

**Comment by gvandam** [comment]
Yes it does when I check out http://purecss.io/ in IE 11 on my Windows 7 VM. For example, when I repeat clicking on Get Started, the menu keeps on sliding in from the left.
