### ISSUE TITLE
Invalid FA CSS fetched by *buttons* page

### ISSUE THREAD

**Issue by peterblazejewicz** [yahoo/pure-site#297]
The Buttons example page has design bug - as it tries to fetch IE7 version of FA - while FA does not support IE7 and relevant file does not exists:

https://github.com/yahoo/pure-site/blob/master/views/pages/buttons.handlebars#L6

https://github.com/FortAwesome/Font-Awesome/pull/2354#issuecomment-27851516
https://github.com/FortAwesome/Font-Awesome/issues/838#issuecomment-25509934

Not sure if fix is as simple as removing offending line though.

**Comment by ericf** [comment]
@peterblazejewicz the fix is that simple. With Pure 0.6.0 we're dropping support for IE7, and therefore there's no reason for Pure's website to need to support IE7 either (especially since it's a developer site.)

**Comment by jamesalley** [comment]
Thanks @peterblazejewicz !

**Comment by peterblazejewicz** [comment]
Thanks guys!
