### ISSUE TITLE
Grid broken in FF at certain zoom level

### ISSUE THREAD

**Issue by jamesalley** [yahoo/pure-site#298]
Because we're using \* border-box rule, and border-box is still a little buggy in various browser implementations, [An Example of Pure Responsive Grids](http://purecss.io/grids/#pure-responsive-grids) (above the mountain scenery) breaks at a certain zoom level. 

So this is a note to myself to apply content-box to the example to fix this corner case.

**Comment by redonkulus** [comment]
Tries this out locally, I'm zooming in to a large size and not seeing any obvious issues.

**Comment by lkraav** [comment]
> Tries this out locally, I'm zooming in to a large size and not seeing any obvious issues.

Fairly certain `display: flex` is more robust in this regard.
