### ISSUE TITLE
Site Menu Disappeared

### ISSUE THREAD

**Issue by macguru2000** [yahoo/pure-site#302]
First off, I want to thank you for incorporating my comments about hiding elements in older versions of Internet Explorer. Thanks.

Now...

I just checked out the latest [Master branch][latest] and noticed while running it locally that the main menu is no longer visible. It seems that two CSS classes for `.pure-menu ul` are responsible for the problem, specifically they set `top` and `left` positions to `-10000px` and `visibility` to `hidden`.

If your already aware of this problem, please feel free to ignore, otherwise I am curious what the intention behind these changes was.

[screenshot](https://cloud.githubusercontent.com/assets/709664/6010140/eb6009b2-aae4-11e4-8858-87697a9f5af8.png)

Cheers!

[latest]: https://github.com/yahoo/pure-site/commit/0709f577d6d5b1d992b7aaef665a937991db0799

**Comment by macguru2000** [comment]
Looked into it a bit more, and it seems that these new changes are from pure itself, not pure-site. Perhaps the menu needs to be re-implemented or this is just an integration bug that will be figured it out.

**Comment by jamesalley** [comment]
@macguru2000 master branch reflects the bleeding edge of Pure. In particular, it includes an entirely new menu construct which would be incompatible with the documentation at http://purecss.io.

Happily, the release candidate is now out. Have a look at the revised website on our staging server, http://stage.purecss.io. You'll see "rc" links there so you can use release candidate files from the CDN.

The new Menus construct  does not have a pure-menu-open class. 

Please review the Menus documentation and the new examples at http://stage.purecss.io and let me know how it works out for you.

Keep in mind that the new Menu construct is not backwards compatible with the old one.

**Comment by jamesalley** [comment]
We'll likely release 0.6.0 proper (not a release candidate) in about a week or so, after giving folks some time to try it out and provide feedback.
