### ISSUE TITLE
stage.purecss.io returns 500

### ISSUE THREAD

**Issue by realistschuckle** [yahoo/pure-site#304]
Looking forward to the new release of pure. Went to http://stage.purecss.io/ and received unhappiness.

## Request
```
GET / HTTP/1.1
Host: stage.purecss.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

## Response
```
500 Internal Server Error
Age: 0
Connection: keep-alive
Content-Length: 21
Content-Type: text/plain
Date: Sun, 08 Feb 2015 17:08:50 GMT
Server: ATS
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
x-content-type-options: nosniff
```

**Comment by okuryu** [comment]
Yeah, it seems to be down for now.

**Comment by okuryu** [comment]
Backed to normal. You can try Pure v0.6.0 RC1. :)

**Comment by jamesalley** [comment]
Sorry about that folks. On Friday I ran into yet another deployment snag, related to deploying the pure-site itself. With power outages all weekend, the fix had to wait till today. We should be all good now, and I hope you enjoy the new Menus and provide plenty of feedback!

**Comment by realistschuckle** [comment]
@jamesalley Thank you! I look forward to trying out the release candidate. Again, many thanks.
