### ISSUE TITLE
Photo Gallery Example use standard grid units?

### ISSUE THREAD

**Issue by jamesalley** [yahoo/pure-site#308]
The Photo Gallery example uses a [custom grid](https://github.com/yahoo/pure-site/blob/master/public/css/layouts/gallery-grid.css). Investigate whether this is truly necessary or whether we can apply the standard grid.

What was customized? The breakpoints? The units themselves? Just double-check, because users were confused as to why the example used classes like `.u-1` instead of `.pure-u-1`.

**Comment by ismarS** [comment]
This is true. 

I've done some tests locally, and the layout works just fine using `pure.css` and `grids-responsive.css`

If it's Ok, I'd like to do PR for this. It's basically replacing the `<link>` for the CSS and replacing all `.u-1` and the rest with `.pure-u-1` etc. Would be my first PR as well :smiley:

**Comment by redonkulus** [comment]
@ismarS go for it!
