### ISSUE TITLE
Clarify pure.css vs pure-nr.css

### ISSUE THREAD

**Issue by jamesalley** [yahoo/pure-site#309]
See https://github.com/yahoo/pure/issues/456

I'm sure many other users have been confused by this.

_Task:_ Clarify the difference between using pure.css and pure-nr.css. Explain what "the regular responsive file" contains. Do we even need a non-responsive file?

**Comment by Kinrany** [comment]
Should purecss.io/customize/ be updated too?

> Rollups consist of all the modules in Pure. There are two rollups available - a regular (responsive) one, and a non-responsive one. Choose that one that's right for your project.

**Comment by redonkulus** [comment]
@Kinrany please feel free to open a pull request to update it.
