### ISSUE TITLE
Mention disabled attribute support in disabled-buttons documentation

### ISSUE THREAD

**Issue by peterblazejewicz** [yahoo/pure-site#316]
http://purecss.io/buttons/#disabled-buttons
https://github.com/yahoo/pure-site/blob/726597f7a85533d11e776f864eea35dcbe9aafa5/views/pages/buttons.handlebars#L26-L28

Can this be updated to reflect `disabled` attribute support (more semantic and pure)?
https://github.com/yahoo/pure/blob/master/src/buttons/css/buttons.css#L35

Thanks!

**Comment by jamesalley** [comment]
That is a reasonable suggestion. Adding it to the work queue for the next release, sometime later this year.

**Comment by peterblazejewicz** [comment]
Thanks!

**Comment by redonkulus** [comment]
@peterblazejewicz This was fixed a while back via the commits referenced above. The Pure site had since been updated http://purecss.io/buttons/#disabled-buttons. Closing this out.
