### ISSUE TITLE
Add sticky footer to documentation

### ISSUE THREAD

**Issue by ghost** [yahoo/pure-site#318]
Sticky footer is amazingly easy in pure.css, per https://github.com/yahoo/pure/issues/387

It took me some googling to find this very helpful code.

If you google http://www.google.com/search?q=sticky+footer+site%3Apurecss.io   ... you'll get no matches.

I suggest sticky footer implementation be added to the website.

**Comment by tlongren** [comment]
Agreed. It's quite a common thing to do (sticky footers), so adding the little bit of code to docs would likely help a lot of folks.

**Comment by baldwmic** [comment]
+1

**Comment by redonkulus** [comment]
Updated the marketing layout example with a sticky footer.
