### ISSUE TITLE
Responsive Images and Flex

### ISSUE THREAD

**Issue by mambax7** [yahoo/pure-site#321]
I followed your recommendation from http://purecss.io/grids/#responsive-images and placed .pure-img on my image:
`<div class="pure-g"><img alt="pure-smacss" class="pure-img" src="https://cdn.tutsplus.com/webdesign/uploads/2013/06/pure-smacss.png" /></div>`

Unfortunately, the image was not responsive:

![image](https://cloud.githubusercontent.com/assets/613686/11459324/e2ae05e0-96a1-11e5-85d1-4824e6d715a0.png)

It became responsive after I turned off "-webkit -flex": 

![image](https://cloud.githubusercontent.com/assets/613686/11459344/90d7b59e-96a2-11e5-99fd-b466b4c54277.png)

This was using Chrome 46.
What am I doing wrong?

**Comment by lkraav** [comment]
Your `<img>` tag is a child of `.pure-g` element, whereas it needs to be a child of a unit element like `.pure-u-1` which concurrently makes it a grandchild of `.pure-g`.
