### ISSUE TITLE
Pure CSS still among the living?

### ISSUE THREAD

**Issue by dhe** [yahoo/pure-site#334]
Sadly no updates anymore?

**Comment by redonkulus** [comment]
It is, but its in the process of transitioning ownership. You can follow the discussion in the [Pure repo](https://github.com/yahoo/pure/issues/557). Closing this out, thanks!

**Comment by redonkulus** [comment]
I'm also working on fixing the internal build pipeline for this repo so that we can get updates out onto the site again.
