### ISSUE TITLE
Code example for rounded inputs was changed to wrong example.

### ISSUE THREAD

**Issue by hperrin** [yahoo/pure-site#370]
https://purecss.io/forms/#rounded-inputs

The code example I'm seeing is for disabled inputs.

![roundedinputs](https://cloud.githubusercontent.com/assets/195918/26609515/5aa7a3c6-4556-11e7-8645-9ea71c17059d.png)

I'm not sure how I got it in this state, but it looks like something changed the element in the DOM. The source came across the network correctly, but by the time I reached that part of the page, it had been changed.

**Comment by redonkulus** [comment]
I can't seem to replicate this. What browser and device are you using?

**Comment by hperrin** [comment]
I don't know. It may have been a bug in my browser or an extension.
