### ISSUE TITLE
Pure version link 404 and jsDelivr needs updated

### ISSUE THREAD

**Issue by fmp777** [yahoo/pure-site#376]
site has 404 on jsDelivr link
![image](https://user-images.githubusercontent.com/2659615/27927560-6eda3984-6249-11e7-8afb-0447fc0efc11.png)

Searching jsdelivr shows only old version 
![image](https://user-images.githubusercontent.com/2659615/27927582-81bf8680-6249-11e7-8943-f87405db42e8.png)

**Comment by jimaek** [comment]
Fixed in https://github.com/yahoo/pure-site/pull/377 Can be closed

**Comment by redonkulus** [comment]
Thanks!
