### ISSUE TITLE
Website is replying 500!

### ISSUE THREAD

**Issue by notorand-it** [yahoo/pure-site#384]
Go try it!

**Comment by redonkulus** [comment]
Looks like Now is having issues: https://twitter.com/zeit_status/status/946436280707174401

**Comment by notorand-it** [comment]
I don't fully understand the link between  https://purecss.io/ (home of pure) and  https://zeit-status.co/ .
But it could easily be just me.

**Comment by redonkulus** [comment]
Sorry for not being clearer. The Pure CSS site is hosted by Zeit, using their Now service. They are having some capacity issues today, thats why the site is down. Once they resolve that, the site should be back up.

**Comment by redonkulus** [comment]
Looks like this is resolved now https://twitter.com/zeit_status/status/946597402483421184

The site is up for me as well. Going to close this.
