### ISSUE TITLE
Provide examples on how to create responsive mobile menus

### ISSUE THREAD

**Issue by tilomitra** [yahoo/pure-site#82]
We should have snippets on the site for how to recreate responsive menus. Off the top of my head:

* slide-out menu (like the one on the site)
* the traditional drop down responsive menu

Let's have example JS snippets for these in jQuery, YUI, and vanilla JS, so people can copy-paste these.

**Comment by jamesalley** [comment]
Last winter I updated Pure Menu and added new responsive examples to the Layouts page.
